PolyBotConversation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("chat.urls")),
    path("admin/", admin.site.urls),
]

chat/urls.py
from django.urls import include, path

from chat import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("user/", views.user, name="user"),
    path("chat/new/", views.chat_new, name="chat_new"),
    path("chat/clear/", views.chat_clear, name="chat_clear"),
    path("chat/<uuid:conversation_uuid>/", views.chat, name="chat"),
    path("<uuid:conversation_uuid>/", views.chat, name="chat"),
    path(
        "<uuid:conversation_uuid>/load_messages/",
        views.load_messages,
        name="load_messages",
    ),
    path(
        "<uuid:conversation_uuid>/send_message/",
        views.send_message,
        name="send_message",
    ),
    path(
        "chat/<uuid:conversation_uuid>/title",
        views.load_conversation_title,
        name="load_conversation_title",
    ),
    path('sidebar/conversations/', 
         views.load_sidebar_conversations, 
         name='load_sidebar_conversations'),
    path('<uuid:conversation_uuid>/sidebar/metrics', views.load_sidebar_metrics, name='load_sidebar_metrics'),
    path(
        "chat/<uuid:conversation_uuid>/manage_bots/",
        views.manage_bots_in_conversation,
        name="manage_bots_in_conversation",
    ),
    path(
        "chat/<uuid:conversation_uuid>/manage_strategies/",
        views.manage_strategies_for_conversation,
        name="manage_strategies_for_conversation",
    ),
    path("chat/<uuid:conversation_uuid>/delete/", views.chat_delete, name="chat_delete"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("chat/<uuid:conversation_uuid>/setup/", views.setup_conversation, name="setup_conversation"),
    path("chat/<uuid:conversation_uuid>/bots/create/", views.create_bot, name="create_bot"),
    path('chat/<uuid:conversation_uuid>/invite', views.invite_users, name='invite_users'),
    path('chat/<uuid:conversation_uuid>/join/', views.join_conversation, name='join_conversation'),
    path('chat/<uuid:conversation_uuid>/manage_settings/', views.manage_settings, name='manage_settings'),
    path('chat/<uuid:conversation_uuid>/settings/create/', views.create_settings, name="create_settings"),
    path('chat/<uuid:conversation_uuid>/finalize/', views.finalize_conversation_setup, name='finalize_conversation_setup'),
    path("chat/<uuid:conversation_uuid>/generate_segments/", views.generate_segments, name="generate_segments"),
]

chat/forms.py
from django import forms

from chat.models import Bot, Strategy, Segment, Settings


class ManageBotsForm(forms.Form):
    bots = forms.ModelMultipleChoiceField(
        queryset=Bot.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label="Select Bots",
    )

class CreateBotForm(forms.ModelForm):
    class Meta:
        model = Bot
        fields = ['name', 'description', 'color', 'model', 'prompt', 'temperature']

class ManageStrategiesForm(forms.Form):
    strategies = forms.ModelMultipleChoiceField(
        queryset=Strategy.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label="Select Strategies",
    )

class ManageSettingsForm(forms.Form):
    settings = forms.ModelChoiceField(
        queryset=Settings.objects.all(),
        widget=forms.Select,
        label="Select Conversation Settings"
    )
    
class CreateSettingsForm(forms.ModelForm):
    class Meta:
        model = Settings
        fields = ['name', 'context', 'duration']
    
    def clean_name(self):
        name = self.cleaned_data['name']
        if Settings.objects.filter(name=name).exists():
            raise forms.ValidationError("A Settings instance with this name already exists.")
        return name

class CreateSegmentForm(forms.ModelForm):
    class Meta:
        model = Segment
        fields = ['name', 'prompt', 'duration_minutes', 'order', 'settings']

chat/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest
from django.contrib.auth import login
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_http_methods, require_POST
from django_q.models import Schedule
from django_q.tasks import schedule
from django.utils import timezone
from django.forms import modelformset_factory

from chat.forms import ManageBotsForm, ManageStrategiesForm, CreateBotForm, CreateSegmentForm, ManageSettingsForm, CreateSettingsForm
from chat.llm import llm_generate_subtopics, llm_generate_segments
from chat.models import Conversation, Message, Participant, User, Strategy, Segment, Settings
from chat.evaluation import get_metrics
from chat.helpers import render_summary

import json
import markdown
from django.utils.safestring import mark_safe

@login_required
def index(request):
    context = {
        "conversations": Conversation.objects.all(),
        "version": settings.VERSION,
    }

    return render(request, "chat/index.html", context)


@login_required
def chat_new(request):
    # Create a new conversation
    conversation = Conversation.objects.create()

    # Create a participant for the logged-in user
    participant, _ = Participant.objects.get_or_create(participant_type="user", user=request.user)
    conversation.participants.add(participant)
    
    # Add by default all strategies
    for strat in Strategy.objects.all():
        conversation.strategies.add(strat)
    
    schedule("chat.tasks.update_conversation_title",
        conversation.id,
        schedule_type="I",
        minutes=2,
        name=f"update_conversation_title_{conversation.id}",
    )
    
    # schedule("chat.tasks.update_conversation_subtopics",
    #     conversation.id,
    #     schedule_type="I",
    #     minutes=0.25,
    #     name=f"update_conversation_subtopics_{conversation.id}",
    # )
    
    schedule("chat.tasks.update_conversation_summary",
        conversation.id,
        schedule_type="I",
        minutes=2,
        name=f"update_conversation_summary_{conversation.id}",
    )
    
    schedule("chat.tasks.update_evaluation_metrics",
        conversation.id,
        schedule_type="I",
        minutes=5,
        name=f"update_evaluation_metrics_{conversation.id}",
    )
    
    return redirect("chat:setup_conversation", conversation_uuid=conversation.uuid)

@login_required
def setup_conversation(request, conversation_uuid):
    conversation = get_object_or_404(Conversation, uuid=conversation_uuid)
    context = {
        "conversation": conversation,
        "version": settings.VERSION,
    }
    return render(request, "chat/setup_conversation.html", context)

@login_required
def finalize_conversation_setup(request, conversation_uuid):
    conversation = get_object_or_404(Conversation, uuid=conversation_uuid)

    if conversation.count_old_participants==0:
        # Update creation timestamp and count of participants
        conversation.created_at = timezone.now()
        conversation.count_old_participants = conversation.participants.count()
        conversation.save()

    return redirect('chat:chat', conversation_uuid=conversation.uuid)

@login_required
def chat(request, conversation_uuid=False):
    # Fetch the conversation instance based on the UUID provided as a query parameter
    conversation = get_object_or_404(Conversation, uuid=conversation_uuid)

    # Retrieve all participants (both users and bots) from the conversation
    participants = conversation.participants.select_related("user", "bot").all()

    # Retrieve all messages for the conversation
    messages = Message.objects.filter(conversation=conversation).select_related("participant__user", "participant__bot").order_by("timestamp")

    # Create the context to pass to the template
    context = {
        "conversations": Conversation.objects.all(),
        "conversation": conversation,
        "messages": messages,
        "participants": participants,
        "version": settings.VERSION,
    }

    return render(request, "chat/chat.html", context)


@login_required
def user(request):
    context = {
        "conversations": Conversation.objects.all(),
        "version": settings.VERSION,
    }

    return render(request, "chat/user.html", context)


@login_required
def load_messages(request, conversation_uuid):
    conversation = get_object_or_404(Conversation, uuid=conversation_uuid)
    messages = Message.objects.filter(conversation=conversation).select_related("participant__user", "participant__bot").order_by("timestamp")
    return render(request, "chat/partials/messages.html", {"messages": messages})


@login_required
def load_conversation_title(request, conversation_uuid):
    conversation = get_object_or_404(Conversation, uuid=conversation_uuid)
    #return HttpResponse(llm_conversation_title(conversation))
    return render(request, "chat/partials/conversation_title.html", {"conversation": conversation})

@login_required
def load_sidebar_conversations(request):
    conversations = Conversation.objects.all().order_by('-creation_date')  # Adjust queryset as needed
    return render(request, 'chat/partials/sidebar_conversations.html', {'conversations': conversations})

@login_required
def load_sidebar_metrics(request, conversation_uuid):
    conversation = get_object_or_404(Conversation, uuid=conversation_uuid)
    rendered_summary = mark_safe(markdown.markdown(conversation.summary)) if conversation.summary else None
    context = {
        "conversation": conversation,
        "metrics": get_metrics(conversation),
        "subtopics": conversation.sub_topics.all(),
        #"summary": render_summary(conversation.summary),
        "summary": rendered_summary,
    }
    return render(request, "chat/partials/metrics.html", context)


@login_required
@require_http_methods(["POST"])
def send_message(request, conversation_uuid):
    conversation = get_object_or_404(Conversation, uuid=conversation_uuid)
    participant = conversation.participants.filter(user=request.user).first()  # Assuming the logged-in user is the sender

    if participant and "message" in request.POST:
        message_content = request.POST["message"]
        Message.objects.create(conversation=conversation, participant=participant, message=message_content)

        # if conversation.triggers.filter(name="mention").exists():
        #     mention(conversation)

    # Return updated messages list
    messages = Message.objects.filter(conversation=conversation).select_related("participant__user", "participant__bot").order_by("timestamp")
    return render(request, "chat/partials/messages.html", {"messages": messages})


@login_required
@require_http_methods(["GET", "POST"])
def manage_bots_in_conversation(request, conversation_uuid):
    conversation = get_object_or_404(Conversation, uuid=conversation_uuid)

    if request.method == "POST":
        form = ManageBotsForm(request.POST)
        if form.is_valid():
            current_bots = conversation.participants.filter(participant_type="bot")
            selected_bots = form.cleaned_data["bots"]

            removed_bots = current_bots.exclude(bot__in=selected_bots)

            for removed_bot in removed_bots:
                conversation.participants.remove(removed_bot)

            for bot in selected_bots:
                participant, created = Participant.objects.get_or_create(participant_type="bot", bot=bot)
                conversation.participants.add(participant)

            return redirect("chat:setup_conversation", conversation_uuid=conversation.uuid)
    else:
        form = ManageBotsForm(initial={"bots": conversation.participants.filter(participant_type="bot").values_list("bot", flat=True)})

    # Create the context to pass to the template
    context = {
        "conversations": Conversation.objects.all(),
        "form": form,
        "conversation": conversation,
        "version": settings.VERSION,
    }

    return render(request, "chat/manage_bots.html", context)

@login_required
@require_http_methods(["GET", "POST"])
def create_bot(request, conversation_uuid):
    conversation = get_object_or_404(Conversation, uuid=conversation_uuid)

    if request.method == "POST":
        form = CreateBotForm(request.POST)
        if form.is_valid():
            new_bot = form.save()

            # Add the new bot to the conversation
            participant, _ = Participant.objects.get_or_create(participant_type="bot", bot=new_bot)
            conversation.participants.add(participant)

            return redirect("chat:manage_bots_in_conversation", conversation_uuid=conversation_uuid)
    else:
        form = CreateBotForm()

    context = {
        "conversation": conversation,
        "form": form,
        "version": settings.VERSION,
    }

    return render(request, "chat/create_bot.html", context)

@login_required
@require_http_methods(["GET", "POST"])
def manage_strategies_for_conversation(request, conversation_uuid):
    conversation = get_object_or_404(Conversation, uuid=conversation_uuid)

    if request.method == "POST":
        form = ManageStrategiesForm(request.POST)
        if form.is_valid():
            current_strategies = conversation.strategies.all()
            selected_strategies = form.cleaned_data["strategies"]

            removed_strategies = current_strategies.exclude(id__in=selected_strategies)

            for removed_strategies in removed_strategies:
                conversation.strategies.remove(removed_strategies)

            for strategy in selected_strategies:
                conversation.strategies.add(strategy)


chat/templates/chat/partials/conversation_title.html
<div id="conversation-title"
     hx-get="{% url 'chat:load_conversation_title' conversation.uuid %}"
     hx-trigger="load, every 60s"
     hx-swap="outerHTML">
    <h1>{{ conversation.title }}</h1>
</div>

chat/templates/chat/partials/messages.html
{% load message_filters %}

<ul class="list-group" id="message-list" style="list-style-type: none; padding: 0;">
    {% for message in messages %}
        <li class="d-flex {% if message.participant.user == request.user %}justify-content-end{% else %}justify-content-start{% endif %} mb-2">
            <div 
                class="{% if message.participant.user == request.user %}user-message{% else %}other-message{% endif %}" 
                style="{% if message.participant.user != request.user %}background-color: {{ message.participant.bot.color }} !important {% endif %}"
            >
                <span class="message-username">
                    {% if message.participant.participant_type == 'user' %}
                        {{ message.participant.user.username }}
                    {% elif message.participant.participant_type == 'bot' %}
                        {{ message.participant.bot.name }} (Bot)
                    {% endif %}
                </span>
                <br>
                {{ message.message|highlight_mentions|render_markdown }}
                <br>
                <span class="message-timestamp">{{ message.timestamp|date:"H:i:s" }}</span>
            </div>
        </li>
    {% empty %}
        <li class="text-center text-muted">No messages yet.</li>
    {% endfor %}
</ul>

chat/templates/chat/partials/metrics.html
<div class="metrics-section p-3">
    <h5>📊 Metrics</h5>
    <ul>
        {% for name, metric in metrics.items %}
            <li>{{ name }} {{ metric }}</li>
        {% empty %}
            <li>No metrics yet.</li>
        {% endfor %}
    </ul>

    <h5>🧩 Subtopics</h5>
    <ul>
        {% for topic in subtopics %}
            <li>{{ topic }}</li>
        {% empty %}
            <li>No subtopics yet.</li>
        {% endfor %}
    </ul>

    <h5>📝 Summary</h5>
    <div>{{ summary|default:"No summary available yet."|linebreaksbr }}</div>
</div>

chat/templates/chat/partials/sidebar.html
<div class="sidebar d-flex flex-column">
    <p class="text-center sidebar-header"><strong>P</strong>oly<strong>B</strong>ot<strong>C</strong>onversation</p>
    <span class="text-center version">{{ version }}</span>

    {% if user.is_authenticated %}
    <div id="sidebar-conversations"
         hx-get="{% url 'chat:load_sidebar_conversations' %}"
         hx-trigger="load, every 60s"
         hx-swap="innerHTML">
        {% include "chat/partials/sidebar_conversations.html" %}
    </div>

    <hr>

    <ul class="nav flex-column">
        <li class="nav-item mt-auto">
            <a class="text-center nav-link" href="{% url 'chat:user' %}">🔧 {{ user.first_name }} {{ user.last_name }}</a>
        </li>
    </ul>

    <div class="nav flex-colum justify-content-center">
        <form class="nav-item" action="{% url 'chat:logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-secondary" style="width:200px; margin: 15px;" type="submit">Log Out</button>
        </form>
    </div>

    <!-- Spacer to push metrics down if page is short -->
    <div style="flex-grow: 1;"></div>

    {% if conversation and conversation.uuid %}
    <!-- Sticky metrics wrapper -->
    <div style="position: relative;">
        <div id="sidebar-metrics"
             class="bg-white p-3 border-top shadow-sm"
             style="position: sticky; bottom: 0; z-index: 10;"
             hx-get="{% url 'chat:load_sidebar_metrics' conversation.uuid %}"
             hx-trigger="load, every 60s"
             hx-swap="innerHTML">
            {% include "chat/partials/metrics.html" %}
        </div>
    </div>
    {% endif %}
    {% endif %}
</div>

chat/templates/chat/partials/sidebar_conversations.html
<p class="sidebar-heading">Conversations</p>
<a href="{% url 'chat:chat_new' %}" style="margin: 15px;" class="nav-item btn btn-light">New Conversation</a>
<ul class="nav flex-column">
    {% for conversation in conversations %}
        <li class="nav-item">
            <a class="nav-link" href="/chat/{{ conversation.uuid }}">
                <span>{{ conversation.title }}</span><br><span class="sidebar-timestamp">{{ conversation.creation_date }}</span>
            </a>
        </li>
    {% empty %}
        <li class="nav-item">
            <span class="nav-link">No conversations available</span>
        </li>
    {% endfor %}
</ul>

<a href="{% url 'chat:chat_clear' %}" style="margin: 15px;" class="nav-item btn btn-danger">Clear Chats</a>